image:
- Visual Studio 2017
- Ubuntu

# Java 10+ not supported by Lombok
stack: jdk 9

cache:
  - '%USERPROFILE%\.m2 -> **\pom.xml'

build_script:
  - mvn package

artifacts:
  - path: '*\target\*.jar'
